backend:
  name: github
  repo: nomoding/nomod-way

media_folder: static/img
public_folder: /img

collections:
  - name: 'category'
    label: 'Category'
    folder: 'src/_data/categories'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'category-post' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'text', required: true }

  - name: 'subcategory'
    label: 'Subcategory'
    folder: 'src/_data/subcategories'
    create: true
    slug: '{{articleCategory}}-{{slug}}'
    identifier_field: subCategoryName
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'subcategory-post',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Category',
          name: 'articleCategory',
          widget: 'relation',
          collection: 'category',
          searchFields: 'title',
          valueField: 'title',
          required: true,
        }
      - {
          label: 'Subcategory Name',
          name: 'subCategoryName',
          widget: 'string',
          hint: 'Please, create this name based on Category name and current Subcategory name. Example: "category-subcategory"',
          required: true,
        }

  - name: 'article'
    label: 'Article'
    folder: 'src/_data/articles'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'article-post' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Content', name: 'body', widget: 'markdown', required: true }
      - {
          label: 'Category',
          name: 'articleCategory',
          widget: 'relation',
          collection: 'category',
          searchFields: 'title',
          valueField: 'title',
          required: true,
        }
      - {
          label: 'SubCategory',
          name: 'articleSubCategory',
          widget: 'relation',
          collection: 'subcategory',
          searchFields: 'subCategoryName',
          displayFields: 'subCategoryName',
          valueField: 'title',
          required: true,
        }
